### ISSUE TITLE
このオープンソースプロジェクトは、Linuxシステムで動作するバージョンがありますか？

### ISSUE THREAD

**Issue by pjmha** [Zuntan03/EasyPromptAnime#1]
このオープンソースプロジェクトは、Linuxシステムで動作するバージョンがありますか？

**Comment by Zuntan03** [comment]
No, there is not.
Windows Batchfile 100%.

![image](https://github.com/Zuntan03/EasyPromptAnime/assets/121656336/0fe16650-0d98-4c61-8726-0a63f43bb701)
